#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Library
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FilmDukkaniDB")]
	public partial class OrmFilmDukkaniDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAdresler(Adresler instance);
    partial void UpdateAdresler(Adresler instance);
    partial void DeleteAdresler(Adresler instance);
    partial void InsertYonetmenler(Yonetmenler instance);
    partial void UpdateYonetmenler(Yonetmenler instance);
    partial void DeleteYonetmenler(Yonetmenler instance);
    partial void InsertCalisanlar(Calisanlar instance);
    partial void UpdateCalisanlar(Calisanlar instance);
    partial void DeleteCalisanlar(Calisanlar instance);
    partial void InsertFilmler(Filmler instance);
    partial void UpdateFilmler(Filmler instance);
    partial void DeleteFilmler(Filmler instance);
    partial void InsertKategoriler(Kategoriler instance);
    partial void UpdateKategoriler(Kategoriler instance);
    partial void DeleteKategoriler(Kategoriler instance);
    partial void InsertMusteriler(Musteriler instance);
    partial void UpdateMusteriler(Musteriler instance);
    partial void DeleteMusteriler(Musteriler instance);
    partial void InsertOyuncular(Oyuncular instance);
    partial void UpdateOyuncular(Oyuncular instance);
    partial void DeleteOyuncular(Oyuncular instance);
    partial void InsertSubeler(Subeler instance);
    partial void UpdateSubeler(Subeler instance);
    partial void DeleteSubeler(Subeler instance);
    #endregion
		
		public OrmFilmDukkaniDBDataContext() : 
				base(global::Web.Library.Properties.Settings.Default.FilmDukkaniDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public OrmFilmDukkaniDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OrmFilmDukkaniDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OrmFilmDukkaniDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OrmFilmDukkaniDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Adresler> Adreslers
		{
			get
			{
				return this.GetTable<Adresler>();
			}
		}
		
		public System.Data.Linq.Table<Yonetmenler> Yonetmenlers
		{
			get
			{
				return this.GetTable<Yonetmenler>();
			}
		}
		
		public System.Data.Linq.Table<Calisanlar> Calisanlars
		{
			get
			{
				return this.GetTable<Calisanlar>();
			}
		}
		
		public System.Data.Linq.Table<Filmler> Filmlers
		{
			get
			{
				return this.GetTable<Filmler>();
			}
		}
		
		public System.Data.Linq.Table<Kategoriler> Kategorilers
		{
			get
			{
				return this.GetTable<Kategoriler>();
			}
		}
		
		public System.Data.Linq.Table<Musteriler> Musterilers
		{
			get
			{
				return this.GetTable<Musteriler>();
			}
		}
		
		public System.Data.Linq.Table<Oyuncular> Oyunculars
		{
			get
			{
				return this.GetTable<Oyuncular>();
			}
		}
		
		public System.Data.Linq.Table<Subeler> Subelers
		{
			get
			{
				return this.GetTable<Subeler>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Adresler")]
	public partial class Adresler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AdresID;
		
		private string _Cadde;
		
		private string _Sokak;
		
		private string _Mahalle;
		
		private int _BinaNo;
		
		private System.Nullable<int> _Kat;
		
		private System.Nullable<int> _DaireNo;
		
		private string _Ilce;
		
		private string _Il;
		
		private string _PostaKodu;
		
		private EntitySet<Calisanlar> _Calisanlars;
		
		private EntitySet<Musteriler> _Musterilers;
		
		private EntitySet<Subeler> _Subelers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAdresIDChanging(int value);
    partial void OnAdresIDChanged();
    partial void OnCaddeChanging(string value);
    partial void OnCaddeChanged();
    partial void OnSokakChanging(string value);
    partial void OnSokakChanged();
    partial void OnMahalleChanging(string value);
    partial void OnMahalleChanged();
    partial void OnBinaNoChanging(int value);
    partial void OnBinaNoChanged();
    partial void OnKatChanging(System.Nullable<int> value);
    partial void OnKatChanged();
    partial void OnDaireNoChanging(System.Nullable<int> value);
    partial void OnDaireNoChanged();
    partial void OnIlceChanging(string value);
    partial void OnIlceChanged();
    partial void OnIlChanging(string value);
    partial void OnIlChanged();
    partial void OnPostaKoduChanging(string value);
    partial void OnPostaKoduChanged();
    #endregion
		
		public Adresler()
		{
			this._Calisanlars = new EntitySet<Calisanlar>(new Action<Calisanlar>(this.attach_Calisanlars), new Action<Calisanlar>(this.detach_Calisanlars));
			this._Musterilers = new EntitySet<Musteriler>(new Action<Musteriler>(this.attach_Musterilers), new Action<Musteriler>(this.detach_Musterilers));
			this._Subelers = new EntitySet<Subeler>(new Action<Subeler>(this.attach_Subelers), new Action<Subeler>(this.detach_Subelers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdresID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AdresID
		{
			get
			{
				return this._AdresID;
			}
			set
			{
				if ((this._AdresID != value))
				{
					this.OnAdresIDChanging(value);
					this.SendPropertyChanging();
					this._AdresID = value;
					this.SendPropertyChanged("AdresID");
					this.OnAdresIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cadde", DbType="NVarChar(50)")]
		public string Cadde
		{
			get
			{
				return this._Cadde;
			}
			set
			{
				if ((this._Cadde != value))
				{
					this.OnCaddeChanging(value);
					this.SendPropertyChanging();
					this._Cadde = value;
					this.SendPropertyChanged("Cadde");
					this.OnCaddeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sokak", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Sokak
		{
			get
			{
				return this._Sokak;
			}
			set
			{
				if ((this._Sokak != value))
				{
					this.OnSokakChanging(value);
					this.SendPropertyChanging();
					this._Sokak = value;
					this.SendPropertyChanged("Sokak");
					this.OnSokakChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mahalle", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Mahalle
		{
			get
			{
				return this._Mahalle;
			}
			set
			{
				if ((this._Mahalle != value))
				{
					this.OnMahalleChanging(value);
					this.SendPropertyChanging();
					this._Mahalle = value;
					this.SendPropertyChanged("Mahalle");
					this.OnMahalleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BinaNo", DbType="Int NOT NULL")]
		public int BinaNo
		{
			get
			{
				return this._BinaNo;
			}
			set
			{
				if ((this._BinaNo != value))
				{
					this.OnBinaNoChanging(value);
					this.SendPropertyChanging();
					this._BinaNo = value;
					this.SendPropertyChanged("BinaNo");
					this.OnBinaNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kat", DbType="Int")]
		public System.Nullable<int> Kat
		{
			get
			{
				return this._Kat;
			}
			set
			{
				if ((this._Kat != value))
				{
					this.OnKatChanging(value);
					this.SendPropertyChanging();
					this._Kat = value;
					this.SendPropertyChanged("Kat");
					this.OnKatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaireNo", DbType="Int")]
		public System.Nullable<int> DaireNo
		{
			get
			{
				return this._DaireNo;
			}
			set
			{
				if ((this._DaireNo != value))
				{
					this.OnDaireNoChanging(value);
					this.SendPropertyChanging();
					this._DaireNo = value;
					this.SendPropertyChanged("DaireNo");
					this.OnDaireNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilce", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Ilce
		{
			get
			{
				return this._Ilce;
			}
			set
			{
				if ((this._Ilce != value))
				{
					this.OnIlceChanging(value);
					this.SendPropertyChanging();
					this._Ilce = value;
					this.SendPropertyChanged("Ilce");
					this.OnIlceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Il", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Il
		{
			get
			{
				return this._Il;
			}
			set
			{
				if ((this._Il != value))
				{
					this.OnIlChanging(value);
					this.SendPropertyChanging();
					this._Il = value;
					this.SendPropertyChanged("Il");
					this.OnIlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostaKodu", DbType="NVarChar(5)")]
		public string PostaKodu
		{
			get
			{
				return this._PostaKodu;
			}
			set
			{
				if ((this._PostaKodu != value))
				{
					this.OnPostaKoduChanging(value);
					this.SendPropertyChanging();
					this._PostaKodu = value;
					this.SendPropertyChanged("PostaKodu");
					this.OnPostaKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Adresler_Calisanlar", Storage="_Calisanlars", ThisKey="AdresID", OtherKey="AdresID")]
		public EntitySet<Calisanlar> Calisanlars
		{
			get
			{
				return this._Calisanlars;
			}
			set
			{
				this._Calisanlars.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Adresler_Musteriler", Storage="_Musterilers", ThisKey="AdresID", OtherKey="AdresID")]
		public EntitySet<Musteriler> Musterilers
		{
			get
			{
				return this._Musterilers;
			}
			set
			{
				this._Musterilers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Adresler_Subeler", Storage="_Subelers", ThisKey="AdresID", OtherKey="AdresID")]
		public EntitySet<Subeler> Subelers
		{
			get
			{
				return this._Subelers;
			}
			set
			{
				this._Subelers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Calisanlars(Calisanlar entity)
		{
			this.SendPropertyChanging();
			entity.Adresler = this;
		}
		
		private void detach_Calisanlars(Calisanlar entity)
		{
			this.SendPropertyChanging();
			entity.Adresler = null;
		}
		
		private void attach_Musterilers(Musteriler entity)
		{
			this.SendPropertyChanging();
			entity.Adresler = this;
		}
		
		private void detach_Musterilers(Musteriler entity)
		{
			this.SendPropertyChanging();
			entity.Adresler = null;
		}
		
		private void attach_Subelers(Subeler entity)
		{
			this.SendPropertyChanging();
			entity.Adresler = this;
		}
		
		private void detach_Subelers(Subeler entity)
		{
			this.SendPropertyChanging();
			entity.Adresler = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Yonetmenler")]
	public partial class Yonetmenler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _YonetmenID;
		
		private string _YonetmenAdi;
		
		private string _YonetmenSoyadi;
		
		private EntitySet<Filmler> _Filmlers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnYonetmenIDChanging(int value);
    partial void OnYonetmenIDChanged();
    partial void OnYonetmenAdiChanging(string value);
    partial void OnYonetmenAdiChanged();
    partial void OnYonetmenSoyadiChanging(string value);
    partial void OnYonetmenSoyadiChanged();
    #endregion
		
		public Yonetmenler()
		{
			this._Filmlers = new EntitySet<Filmler>(new Action<Filmler>(this.attach_Filmlers), new Action<Filmler>(this.detach_Filmlers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YonetmenID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int YonetmenID
		{
			get
			{
				return this._YonetmenID;
			}
			set
			{
				if ((this._YonetmenID != value))
				{
					this.OnYonetmenIDChanging(value);
					this.SendPropertyChanging();
					this._YonetmenID = value;
					this.SendPropertyChanged("YonetmenID");
					this.OnYonetmenIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YonetmenAdi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string YonetmenAdi
		{
			get
			{
				return this._YonetmenAdi;
			}
			set
			{
				if ((this._YonetmenAdi != value))
				{
					this.OnYonetmenAdiChanging(value);
					this.SendPropertyChanging();
					this._YonetmenAdi = value;
					this.SendPropertyChanged("YonetmenAdi");
					this.OnYonetmenAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YonetmenSoyadi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string YonetmenSoyadi
		{
			get
			{
				return this._YonetmenSoyadi;
			}
			set
			{
				if ((this._YonetmenSoyadi != value))
				{
					this.OnYonetmenSoyadiChanging(value);
					this.SendPropertyChanging();
					this._YonetmenSoyadi = value;
					this.SendPropertyChanged("YonetmenSoyadi");
					this.OnYonetmenSoyadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Yonetmenler_Filmler", Storage="_Filmlers", ThisKey="YonetmenID", OtherKey="YonetmenID")]
		public EntitySet<Filmler> Filmlers
		{
			get
			{
				return this._Filmlers;
			}
			set
			{
				this._Filmlers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Filmlers(Filmler entity)
		{
			this.SendPropertyChanging();
			entity.Yonetmenler = this;
		}
		
		private void detach_Filmlers(Filmler entity)
		{
			this.SendPropertyChanging();
			entity.Yonetmenler = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Calisanlar")]
	public partial class Calisanlar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CalisanID;
		
		private string _CalisanAdi;
		
		private string _CalisanSoyadi;
		
		private string _Cinsiyet;
		
		private string _Telefon;
		
		private string _Email;
		
		private string _Pozisyon;
		
		private int _AdresID;
		
		private int _SubeID;
		
		private string _Fotograf;
		
		private string _Sifre;
		
		private EntityRef<Adresler> _Adresler;
		
		private EntityRef<Subeler> _Subeler;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCalisanIDChanging(int value);
    partial void OnCalisanIDChanged();
    partial void OnCalisanAdiChanging(string value);
    partial void OnCalisanAdiChanged();
    partial void OnCalisanSoyadiChanging(string value);
    partial void OnCalisanSoyadiChanged();
    partial void OnCinsiyetChanging(string value);
    partial void OnCinsiyetChanged();
    partial void OnTelefonChanging(string value);
    partial void OnTelefonChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPozisyonChanging(string value);
    partial void OnPozisyonChanged();
    partial void OnAdresIDChanging(int value);
    partial void OnAdresIDChanged();
    partial void OnSubeIDChanging(int value);
    partial void OnSubeIDChanged();
    partial void OnFotografChanging(string value);
    partial void OnFotografChanged();
    partial void OnSifreChanging(string value);
    partial void OnSifreChanged();
    #endregion
		
		public Calisanlar()
		{
			this._Adresler = default(EntityRef<Adresler>);
			this._Subeler = default(EntityRef<Subeler>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalisanID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CalisanID
		{
			get
			{
				return this._CalisanID;
			}
			set
			{
				if ((this._CalisanID != value))
				{
					this.OnCalisanIDChanging(value);
					this.SendPropertyChanging();
					this._CalisanID = value;
					this.SendPropertyChanged("CalisanID");
					this.OnCalisanIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalisanAdi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CalisanAdi
		{
			get
			{
				return this._CalisanAdi;
			}
			set
			{
				if ((this._CalisanAdi != value))
				{
					this.OnCalisanAdiChanging(value);
					this.SendPropertyChanging();
					this._CalisanAdi = value;
					this.SendPropertyChanged("CalisanAdi");
					this.OnCalisanAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalisanSoyadi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CalisanSoyadi
		{
			get
			{
				return this._CalisanSoyadi;
			}
			set
			{
				if ((this._CalisanSoyadi != value))
				{
					this.OnCalisanSoyadiChanging(value);
					this.SendPropertyChanging();
					this._CalisanSoyadi = value;
					this.SendPropertyChanged("CalisanSoyadi");
					this.OnCalisanSoyadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cinsiyet", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Cinsiyet
		{
			get
			{
				return this._Cinsiyet;
			}
			set
			{
				if ((this._Cinsiyet != value))
				{
					this.OnCinsiyetChanging(value);
					this.SendPropertyChanging();
					this._Cinsiyet = value;
					this.SendPropertyChanged("Cinsiyet");
					this.OnCinsiyetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Telefon
		{
			get
			{
				return this._Telefon;
			}
			set
			{
				if ((this._Telefon != value))
				{
					this.OnTelefonChanging(value);
					this.SendPropertyChanging();
					this._Telefon = value;
					this.SendPropertyChanged("Telefon");
					this.OnTelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pozisyon", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Pozisyon
		{
			get
			{
				return this._Pozisyon;
			}
			set
			{
				if ((this._Pozisyon != value))
				{
					this.OnPozisyonChanging(value);
					this.SendPropertyChanging();
					this._Pozisyon = value;
					this.SendPropertyChanged("Pozisyon");
					this.OnPozisyonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdresID", DbType="Int NOT NULL")]
		public int AdresID
		{
			get
			{
				return this._AdresID;
			}
			set
			{
				if ((this._AdresID != value))
				{
					if (this._Adresler.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAdresIDChanging(value);
					this.SendPropertyChanging();
					this._AdresID = value;
					this.SendPropertyChanged("AdresID");
					this.OnAdresIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubeID", DbType="Int NOT NULL")]
		public int SubeID
		{
			get
			{
				return this._SubeID;
			}
			set
			{
				if ((this._SubeID != value))
				{
					if (this._Subeler.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSubeIDChanging(value);
					this.SendPropertyChanging();
					this._SubeID = value;
					this.SendPropertyChanged("SubeID");
					this.OnSubeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fotograf", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string Fotograf
		{
			get
			{
				return this._Fotograf;
			}
			set
			{
				if ((this._Fotograf != value))
				{
					this.OnFotografChanging(value);
					this.SendPropertyChanging();
					this._Fotograf = value;
					this.SendPropertyChanged("Fotograf");
					this.OnFotografChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sifre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Sifre
		{
			get
			{
				return this._Sifre;
			}
			set
			{
				if ((this._Sifre != value))
				{
					this.OnSifreChanging(value);
					this.SendPropertyChanging();
					this._Sifre = value;
					this.SendPropertyChanged("Sifre");
					this.OnSifreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Adresler_Calisanlar", Storage="_Adresler", ThisKey="AdresID", OtherKey="AdresID", IsForeignKey=true)]
		public Adresler Adresler
		{
			get
			{
				return this._Adresler.Entity;
			}
			set
			{
				Adresler previousValue = this._Adresler.Entity;
				if (((previousValue != value) 
							|| (this._Adresler.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Adresler.Entity = null;
						previousValue.Calisanlars.Remove(this);
					}
					this._Adresler.Entity = value;
					if ((value != null))
					{
						value.Calisanlars.Add(this);
						this._AdresID = value.AdresID;
					}
					else
					{
						this._AdresID = default(int);
					}
					this.SendPropertyChanged("Adresler");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Subeler_Calisanlar", Storage="_Subeler", ThisKey="SubeID", OtherKey="SubeID", IsForeignKey=true)]
		public Subeler Subeler
		{
			get
			{
				return this._Subeler.Entity;
			}
			set
			{
				Subeler previousValue = this._Subeler.Entity;
				if (((previousValue != value) 
							|| (this._Subeler.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Subeler.Entity = null;
						previousValue.Calisanlars.Remove(this);
					}
					this._Subeler.Entity = value;
					if ((value != null))
					{
						value.Calisanlars.Add(this);
						this._SubeID = value.SubeID;
					}
					else
					{
						this._SubeID = default(int);
					}
					this.SendPropertyChanged("Subeler");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Filmler")]
	public partial class Filmler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _FilmID;
		
		private string _FilmAdi;
		
		private int _YonetmenID;
		
		private int _KategoriID;
		
		private int _OyuncuID;
		
		private string _Ozet;
		
		private System.DateTime _YapimYili;
		
		private string _Resim;
		
		private string _Odul;
		
		private int _SubeID;
		
		private string _Sure;
		
		private decimal _Fiyat;
		
		private int _StokMiktari;
		
		private string _Fragman;
		
		private EntityRef<Yonetmenler> _Yonetmenler;
		
		private EntityRef<Kategoriler> _Kategoriler;
		
		private EntityRef<Oyuncular> _Oyuncular;
		
		private EntityRef<Subeler> _Subeler;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFilmIDChanging(int value);
    partial void OnFilmIDChanged();
    partial void OnFilmAdiChanging(string value);
    partial void OnFilmAdiChanged();
    partial void OnYonetmenIDChanging(int value);
    partial void OnYonetmenIDChanged();
    partial void OnKategoriIDChanging(int value);
    partial void OnKategoriIDChanged();
    partial void OnOyuncuIDChanging(int value);
    partial void OnOyuncuIDChanged();
    partial void OnOzetChanging(string value);
    partial void OnOzetChanged();
    partial void OnYapimYiliChanging(System.DateTime value);
    partial void OnYapimYiliChanged();
    partial void OnResimChanging(string value);
    partial void OnResimChanged();
    partial void OnOdulChanging(string value);
    partial void OnOdulChanged();
    partial void OnSubeIDChanging(int value);
    partial void OnSubeIDChanged();
    partial void OnSureChanging(string value);
    partial void OnSureChanged();
    partial void OnFiyatChanging(decimal value);
    partial void OnFiyatChanged();
    partial void OnStokMiktariChanging(int value);
    partial void OnStokMiktariChanged();
    partial void OnFragmanChanging(string value);
    partial void OnFragmanChanged();
    #endregion
		
		public Filmler()
		{
			this._Yonetmenler = default(EntityRef<Yonetmenler>);
			this._Kategoriler = default(EntityRef<Kategoriler>);
			this._Oyuncular = default(EntityRef<Oyuncular>);
			this._Subeler = default(EntityRef<Subeler>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FilmID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int FilmID
		{
			get
			{
				return this._FilmID;
			}
			set
			{
				if ((this._FilmID != value))
				{
					this.OnFilmIDChanging(value);
					this.SendPropertyChanging();
					this._FilmID = value;
					this.SendPropertyChanged("FilmID");
					this.OnFilmIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FilmAdi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string FilmAdi
		{
			get
			{
				return this._FilmAdi;
			}
			set
			{
				if ((this._FilmAdi != value))
				{
					this.OnFilmAdiChanging(value);
					this.SendPropertyChanging();
					this._FilmAdi = value;
					this.SendPropertyChanged("FilmAdi");
					this.OnFilmAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YonetmenID", DbType="Int NOT NULL")]
		public int YonetmenID
		{
			get
			{
				return this._YonetmenID;
			}
			set
			{
				if ((this._YonetmenID != value))
				{
					if (this._Yonetmenler.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnYonetmenIDChanging(value);
					this.SendPropertyChanging();
					this._YonetmenID = value;
					this.SendPropertyChanged("YonetmenID");
					this.OnYonetmenIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KategoriID", DbType="Int NOT NULL")]
		public int KategoriID
		{
			get
			{
				return this._KategoriID;
			}
			set
			{
				if ((this._KategoriID != value))
				{
					if (this._Kategoriler.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKategoriIDChanging(value);
					this.SendPropertyChanging();
					this._KategoriID = value;
					this.SendPropertyChanged("KategoriID");
					this.OnKategoriIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OyuncuID", DbType="Int NOT NULL")]
		public int OyuncuID
		{
			get
			{
				return this._OyuncuID;
			}
			set
			{
				if ((this._OyuncuID != value))
				{
					if (this._Oyuncular.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnOyuncuIDChanging(value);
					this.SendPropertyChanging();
					this._OyuncuID = value;
					this.SendPropertyChanged("OyuncuID");
					this.OnOyuncuIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ozet", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Ozet
		{
			get
			{
				return this._Ozet;
			}
			set
			{
				if ((this._Ozet != value))
				{
					this.OnOzetChanging(value);
					this.SendPropertyChanging();
					this._Ozet = value;
					this.SendPropertyChanged("Ozet");
					this.OnOzetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YapimYili", DbType="DateTime NOT NULL")]
		public System.DateTime YapimYili
		{
			get
			{
				return this._YapimYili;
			}
			set
			{
				if ((this._YapimYili != value))
				{
					this.OnYapimYiliChanging(value);
					this.SendPropertyChanging();
					this._YapimYili = value;
					this.SendPropertyChanged("YapimYili");
					this.OnYapimYiliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resim", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string Resim
		{
			get
			{
				return this._Resim;
			}
			set
			{
				if ((this._Resim != value))
				{
					this.OnResimChanging(value);
					this.SendPropertyChanging();
					this._Resim = value;
					this.SendPropertyChanged("Resim");
					this.OnResimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Odul", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Odul
		{
			get
			{
				return this._Odul;
			}
			set
			{
				if ((this._Odul != value))
				{
					this.OnOdulChanging(value);
					this.SendPropertyChanging();
					this._Odul = value;
					this.SendPropertyChanged("Odul");
					this.OnOdulChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubeID", DbType="Int NOT NULL")]
		public int SubeID
		{
			get
			{
				return this._SubeID;
			}
			set
			{
				if ((this._SubeID != value))
				{
					if (this._Subeler.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSubeIDChanging(value);
					this.SendPropertyChanging();
					this._SubeID = value;
					this.SendPropertyChanged("SubeID");
					this.OnSubeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sure", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Sure
		{
			get
			{
				return this._Sure;
			}
			set
			{
				if ((this._Sure != value))
				{
					this.OnSureChanging(value);
					this.SendPropertyChanging();
					this._Sure = value;
					this.SendPropertyChanged("Sure");
					this.OnSureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fiyat", DbType="Money NOT NULL")]
		public decimal Fiyat
		{
			get
			{
				return this._Fiyat;
			}
			set
			{
				if ((this._Fiyat != value))
				{
					this.OnFiyatChanging(value);
					this.SendPropertyChanging();
					this._Fiyat = value;
					this.SendPropertyChanged("Fiyat");
					this.OnFiyatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokMiktari", DbType="Int NOT NULL")]
		public int StokMiktari
		{
			get
			{
				return this._StokMiktari;
			}
			set
			{
				if ((this._StokMiktari != value))
				{
					this.OnStokMiktariChanging(value);
					this.SendPropertyChanging();
					this._StokMiktari = value;
					this.SendPropertyChanged("StokMiktari");
					this.OnStokMiktariChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fragman", DbType="NVarChar(50)")]
		public string Fragman
		{
			get
			{
				return this._Fragman;
			}
			set
			{
				if ((this._Fragman != value))
				{
					this.OnFragmanChanging(value);
					this.SendPropertyChanging();
					this._Fragman = value;
					this.SendPropertyChanged("Fragman");
					this.OnFragmanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Yonetmenler_Filmler", Storage="_Yonetmenler", ThisKey="YonetmenID", OtherKey="YonetmenID", IsForeignKey=true)]
		public Yonetmenler Yonetmenler
		{
			get
			{
				return this._Yonetmenler.Entity;
			}
			set
			{
				Yonetmenler previousValue = this._Yonetmenler.Entity;
				if (((previousValue != value) 
							|| (this._Yonetmenler.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Yonetmenler.Entity = null;
						previousValue.Filmlers.Remove(this);
					}
					this._Yonetmenler.Entity = value;
					if ((value != null))
					{
						value.Filmlers.Add(this);
						this._YonetmenID = value.YonetmenID;
					}
					else
					{
						this._YonetmenID = default(int);
					}
					this.SendPropertyChanged("Yonetmenler");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kategoriler_Filmler", Storage="_Kategoriler", ThisKey="KategoriID", OtherKey="KategoriID", IsForeignKey=true)]
		public Kategoriler Kategoriler
		{
			get
			{
				return this._Kategoriler.Entity;
			}
			set
			{
				Kategoriler previousValue = this._Kategoriler.Entity;
				if (((previousValue != value) 
							|| (this._Kategoriler.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Kategoriler.Entity = null;
						previousValue.Filmlers.Remove(this);
					}
					this._Kategoriler.Entity = value;
					if ((value != null))
					{
						value.Filmlers.Add(this);
						this._KategoriID = value.KategoriID;
					}
					else
					{
						this._KategoriID = default(int);
					}
					this.SendPropertyChanged("Kategoriler");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Oyuncular_Filmler", Storage="_Oyuncular", ThisKey="OyuncuID", OtherKey="OyuncuID", IsForeignKey=true)]
		public Oyuncular Oyuncular
		{
			get
			{
				return this._Oyuncular.Entity;
			}
			set
			{
				Oyuncular previousValue = this._Oyuncular.Entity;
				if (((previousValue != value) 
							|| (this._Oyuncular.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Oyuncular.Entity = null;
						previousValue.Filmlers.Remove(this);
					}
					this._Oyuncular.Entity = value;
					if ((value != null))
					{
						value.Filmlers.Add(this);
						this._OyuncuID = value.OyuncuID;
					}
					else
					{
						this._OyuncuID = default(int);
					}
					this.SendPropertyChanged("Oyuncular");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Subeler_Filmler", Storage="_Subeler", ThisKey="SubeID", OtherKey="SubeID", IsForeignKey=true)]
		public Subeler Subeler
		{
			get
			{
				return this._Subeler.Entity;
			}
			set
			{
				Subeler previousValue = this._Subeler.Entity;
				if (((previousValue != value) 
							|| (this._Subeler.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Subeler.Entity = null;
						previousValue.Filmlers.Remove(this);
					}
					this._Subeler.Entity = value;
					if ((value != null))
					{
						value.Filmlers.Add(this);
						this._SubeID = value.SubeID;
					}
					else
					{
						this._SubeID = default(int);
					}
					this.SendPropertyChanged("Subeler");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kategoriler")]
	public partial class Kategoriler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _KategoriID;
		
		private string _KategoriAdi;
		
		private EntitySet<Filmler> _Filmlers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKategoriIDChanging(int value);
    partial void OnKategoriIDChanged();
    partial void OnKategoriAdiChanging(string value);
    partial void OnKategoriAdiChanged();
    #endregion
		
		public Kategoriler()
		{
			this._Filmlers = new EntitySet<Filmler>(new Action<Filmler>(this.attach_Filmlers), new Action<Filmler>(this.detach_Filmlers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KategoriID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int KategoriID
		{
			get
			{
				return this._KategoriID;
			}
			set
			{
				if ((this._KategoriID != value))
				{
					this.OnKategoriIDChanging(value);
					this.SendPropertyChanging();
					this._KategoriID = value;
					this.SendPropertyChanged("KategoriID");
					this.OnKategoriIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KategoriAdi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string KategoriAdi
		{
			get
			{
				return this._KategoriAdi;
			}
			set
			{
				if ((this._KategoriAdi != value))
				{
					this.OnKategoriAdiChanging(value);
					this.SendPropertyChanging();
					this._KategoriAdi = value;
					this.SendPropertyChanged("KategoriAdi");
					this.OnKategoriAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kategoriler_Filmler", Storage="_Filmlers", ThisKey="KategoriID", OtherKey="KategoriID")]
		public EntitySet<Filmler> Filmlers
		{
			get
			{
				return this._Filmlers;
			}
			set
			{
				this._Filmlers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Filmlers(Filmler entity)
		{
			this.SendPropertyChanging();
			entity.Kategoriler = this;
		}
		
		private void detach_Filmlers(Filmler entity)
		{
			this.SendPropertyChanging();
			entity.Kategoriler = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Musteriler")]
	public partial class Musteriler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MusteriID;
		
		private string _MusteriAdi;
		
		private string _MusteriSoyadi;
		
		private int _AdresID;
		
		private string _Email;
		
		private string _Telefon;
		
		private string _Sifre;
		
		private EntityRef<Adresler> _Adresler;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMusteriIDChanging(int value);
    partial void OnMusteriIDChanged();
    partial void OnMusteriAdiChanging(string value);
    partial void OnMusteriAdiChanged();
    partial void OnMusteriSoyadiChanging(string value);
    partial void OnMusteriSoyadiChanged();
    partial void OnAdresIDChanging(int value);
    partial void OnAdresIDChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnTelefonChanging(string value);
    partial void OnTelefonChanged();
    partial void OnSifreChanging(string value);
    partial void OnSifreChanged();
    #endregion
		
		public Musteriler()
		{
			this._Adresler = default(EntityRef<Adresler>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MusteriID
		{
			get
			{
				return this._MusteriID;
			}
			set
			{
				if ((this._MusteriID != value))
				{
					this.OnMusteriIDChanging(value);
					this.SendPropertyChanging();
					this._MusteriID = value;
					this.SendPropertyChanged("MusteriID");
					this.OnMusteriIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriAdi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MusteriAdi
		{
			get
			{
				return this._MusteriAdi;
			}
			set
			{
				if ((this._MusteriAdi != value))
				{
					this.OnMusteriAdiChanging(value);
					this.SendPropertyChanging();
					this._MusteriAdi = value;
					this.SendPropertyChanged("MusteriAdi");
					this.OnMusteriAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriSoyadi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MusteriSoyadi
		{
			get
			{
				return this._MusteriSoyadi;
			}
			set
			{
				if ((this._MusteriSoyadi != value))
				{
					this.OnMusteriSoyadiChanging(value);
					this.SendPropertyChanging();
					this._MusteriSoyadi = value;
					this.SendPropertyChanged("MusteriSoyadi");
					this.OnMusteriSoyadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdresID", DbType="Int NOT NULL")]
		public int AdresID
		{
			get
			{
				return this._AdresID;
			}
			set
			{
				if ((this._AdresID != value))
				{
					if (this._Adresler.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAdresIDChanging(value);
					this.SendPropertyChanging();
					this._AdresID = value;
					this.SendPropertyChanged("AdresID");
					this.OnAdresIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Telefon
		{
			get
			{
				return this._Telefon;
			}
			set
			{
				if ((this._Telefon != value))
				{
					this.OnTelefonChanging(value);
					this.SendPropertyChanging();
					this._Telefon = value;
					this.SendPropertyChanged("Telefon");
					this.OnTelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sifre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Sifre
		{
			get
			{
				return this._Sifre;
			}
			set
			{
				if ((this._Sifre != value))
				{
					this.OnSifreChanging(value);
					this.SendPropertyChanging();
					this._Sifre = value;
					this.SendPropertyChanged("Sifre");
					this.OnSifreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Adresler_Musteriler", Storage="_Adresler", ThisKey="AdresID", OtherKey="AdresID", IsForeignKey=true)]
		public Adresler Adresler
		{
			get
			{
				return this._Adresler.Entity;
			}
			set
			{
				Adresler previousValue = this._Adresler.Entity;
				if (((previousValue != value) 
							|| (this._Adresler.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Adresler.Entity = null;
						previousValue.Musterilers.Remove(this);
					}
					this._Adresler.Entity = value;
					if ((value != null))
					{
						value.Musterilers.Add(this);
						this._AdresID = value.AdresID;
					}
					else
					{
						this._AdresID = default(int);
					}
					this.SendPropertyChanged("Adresler");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Oyuncular")]
	public partial class Oyuncular : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _OyuncuID;
		
		private string _OyuncuAdi;
		
		private string _OyuncuSoyadi;
		
		private EntitySet<Filmler> _Filmlers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOyuncuIDChanging(int value);
    partial void OnOyuncuIDChanged();
    partial void OnOyuncuAdiChanging(string value);
    partial void OnOyuncuAdiChanged();
    partial void OnOyuncuSoyadiChanging(string value);
    partial void OnOyuncuSoyadiChanged();
    #endregion
		
		public Oyuncular()
		{
			this._Filmlers = new EntitySet<Filmler>(new Action<Filmler>(this.attach_Filmlers), new Action<Filmler>(this.detach_Filmlers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OyuncuID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int OyuncuID
		{
			get
			{
				return this._OyuncuID;
			}
			set
			{
				if ((this._OyuncuID != value))
				{
					this.OnOyuncuIDChanging(value);
					this.SendPropertyChanging();
					this._OyuncuID = value;
					this.SendPropertyChanged("OyuncuID");
					this.OnOyuncuIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OyuncuAdi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string OyuncuAdi
		{
			get
			{
				return this._OyuncuAdi;
			}
			set
			{
				if ((this._OyuncuAdi != value))
				{
					this.OnOyuncuAdiChanging(value);
					this.SendPropertyChanging();
					this._OyuncuAdi = value;
					this.SendPropertyChanged("OyuncuAdi");
					this.OnOyuncuAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OyuncuSoyadi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string OyuncuSoyadi
		{
			get
			{
				return this._OyuncuSoyadi;
			}
			set
			{
				if ((this._OyuncuSoyadi != value))
				{
					this.OnOyuncuSoyadiChanging(value);
					this.SendPropertyChanging();
					this._OyuncuSoyadi = value;
					this.SendPropertyChanged("OyuncuSoyadi");
					this.OnOyuncuSoyadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Oyuncular_Filmler", Storage="_Filmlers", ThisKey="OyuncuID", OtherKey="OyuncuID")]
		public EntitySet<Filmler> Filmlers
		{
			get
			{
				return this._Filmlers;
			}
			set
			{
				this._Filmlers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Filmlers(Filmler entity)
		{
			this.SendPropertyChanging();
			entity.Oyuncular = this;
		}
		
		private void detach_Filmlers(Filmler entity)
		{
			this.SendPropertyChanging();
			entity.Oyuncular = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Subeler")]
	public partial class Subeler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SubeID;
		
		private string _SubeAdi;
		
		private int _AdresID;
		
		private EntitySet<Calisanlar> _Calisanlars;
		
		private EntitySet<Filmler> _Filmlers;
		
		private EntityRef<Adresler> _Adresler;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSubeIDChanging(int value);
    partial void OnSubeIDChanged();
    partial void OnSubeAdiChanging(string value);
    partial void OnSubeAdiChanged();
    partial void OnAdresIDChanging(int value);
    partial void OnAdresIDChanged();
    #endregion
		
		public Subeler()
		{
			this._Calisanlars = new EntitySet<Calisanlar>(new Action<Calisanlar>(this.attach_Calisanlars), new Action<Calisanlar>(this.detach_Calisanlars));
			this._Filmlers = new EntitySet<Filmler>(new Action<Filmler>(this.attach_Filmlers), new Action<Filmler>(this.detach_Filmlers));
			this._Adresler = default(EntityRef<Adresler>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubeID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SubeID
		{
			get
			{
				return this._SubeID;
			}
			set
			{
				if ((this._SubeID != value))
				{
					this.OnSubeIDChanging(value);
					this.SendPropertyChanging();
					this._SubeID = value;
					this.SendPropertyChanged("SubeID");
					this.OnSubeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubeAdi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SubeAdi
		{
			get
			{
				return this._SubeAdi;
			}
			set
			{
				if ((this._SubeAdi != value))
				{
					this.OnSubeAdiChanging(value);
					this.SendPropertyChanging();
					this._SubeAdi = value;
					this.SendPropertyChanged("SubeAdi");
					this.OnSubeAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdresID", DbType="Int NOT NULL")]
		public int AdresID
		{
			get
			{
				return this._AdresID;
			}
			set
			{
				if ((this._AdresID != value))
				{
					if (this._Adresler.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAdresIDChanging(value);
					this.SendPropertyChanging();
					this._AdresID = value;
					this.SendPropertyChanged("AdresID");
					this.OnAdresIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Subeler_Calisanlar", Storage="_Calisanlars", ThisKey="SubeID", OtherKey="SubeID")]
		public EntitySet<Calisanlar> Calisanlars
		{
			get
			{
				return this._Calisanlars;
			}
			set
			{
				this._Calisanlars.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Subeler_Filmler", Storage="_Filmlers", ThisKey="SubeID", OtherKey="SubeID")]
		public EntitySet<Filmler> Filmlers
		{
			get
			{
				return this._Filmlers;
			}
			set
			{
				this._Filmlers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Adresler_Subeler", Storage="_Adresler", ThisKey="AdresID", OtherKey="AdresID", IsForeignKey=true)]
		public Adresler Adresler
		{
			get
			{
				return this._Adresler.Entity;
			}
			set
			{
				Adresler previousValue = this._Adresler.Entity;
				if (((previousValue != value) 
							|| (this._Adresler.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Adresler.Entity = null;
						previousValue.Subelers.Remove(this);
					}
					this._Adresler.Entity = value;
					if ((value != null))
					{
						value.Subelers.Add(this);
						this._AdresID = value.AdresID;
					}
					else
					{
						this._AdresID = default(int);
					}
					this.SendPropertyChanged("Adresler");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Calisanlars(Calisanlar entity)
		{
			this.SendPropertyChanging();
			entity.Subeler = this;
		}
		
		private void detach_Calisanlars(Calisanlar entity)
		{
			this.SendPropertyChanging();
			entity.Subeler = null;
		}
		
		private void attach_Filmlers(Filmler entity)
		{
			this.SendPropertyChanging();
			entity.Subeler = this;
		}
		
		private void detach_Filmlers(Filmler entity)
		{
			this.SendPropertyChanging();
			entity.Subeler = null;
		}
	}
}
#pragma warning restore 1591
